security:
  enable_authenticator_manager: true

  password_hashers:
    App\Entity\Admin:
      algorithm: auto
    #-----------------
    App\Entity\Seller:
      algorithm: auto
    #-----------------
    App\Entity\Customer:
      algorithm: auto

  providers:
    app_admin_provider:
      entity:
        class: App\Entity\Admin
        property: email
    #-----------------
    app_customer_provider:
      entity:
        class: App\Entity\Customer
        property: mobile
    #-----------------
    app_seller_provider:
      entity:
        class: App\Entity\Seller
        property: username

  firewalls:
    admin:
      pattern: ^/admin/
      provider: app_admin_provider
      stateless: true
      jwt: ~
      json_login:
        check_path: /admin/security/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    #-----------------
    carrier:
      pattern: ^/carrier/
      provider: app_admin_provider
      stateless: true
      jwt: ~
      json_login:
        check_path: /carrier/security/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    #-----------------
    seller:
      pattern: ^/seller/
      provider: app_seller_provider
      stateless: true
      jwt: ~
      json_login:
        check_path: /seller/security/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    #-----------------
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    #-----------------
    main:
      pattern: ^((?!/places|/gateways/online).)*$
      stateless: true
      provider: app_customer_provider
      jwt: ~

  access_control:
    - { path: ^/auth/refresh, roles: PUBLIC_ACCESS }
    - { path: ^/seller/auth/refresh, roles: PUBLIC_ACCESS }
    - { path: ^/admin/auth/refresh, roles: PUBLIC_ACCESS }
    - { path: ^/seller/, roles: ROLE_SELLER }
    - { path: ^/admin/, roles: ROLE_ADMIN }
    - { path: ^/(orders|auth/me|customers|customer-addresses|wishlists), roles: ROLE_USER }
    - { path: ^/cart/[^/]+, roles: ROLE_USER }
    - { path: ^/wallet, roles: ROLE_USER }
