<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20201020060254 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admins (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, family VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, mobile VARCHAR(255) NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_A2E0150FE7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE brands (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, subtitle VARCHAR(255) NOT NULL, meta_description LONGTEXT DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_7EA244342B36786B (title), UNIQUE INDEX UNIQ_7EA2443477153098 (code), UNIQUE INDEX UNIQ_7EA24434518597B1 (subtitle), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cart_items (id INT AUTO_INCREMENT NOT NULL, inventory_id INT NOT NULL, cart_id VARCHAR(36) NOT NULL, subtotal BIGINT UNSIGNED NOT NULL, grand_total BIGINT UNSIGNED NOT NULL, price BIGINT UNSIGNED NOT NULL, quantity INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_BEF484459EEA759 (inventory_id), INDEX IDX_BEF484451AD5CDBF (cart_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE carts (id VARCHAR(36) NOT NULL, customer_id INT DEFAULT NULL, subtotal BIGINT UNSIGNED NOT NULL, grand_total BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_4E004AAC9395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE categories (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, subtitle VARCHAR(255) NOT NULL, level INT DEFAULT NULL, configurations LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_3AF346682B36786B (title), UNIQUE INDEX UNIQ_3AF34668518597B1 (subtitle), INDEX IDX_3AF34668727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_closures (id INT AUTO_INCREMENT NOT NULL, ancestor INT NOT NULL, descendant INT NOT NULL, depth INT NOT NULL, INDEX IDX_5DE8AEBFB4465BB (ancestor), INDEX IDX_5DE8AEBF9A8FAD16 (descendant), INDEX IDX_7AEF6B6FD3087B6C (depth), UNIQUE INDEX IDX_EA6C9A627F768DDD (ancestor, descendant), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_commissions (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, fee DOUBLE PRECISION NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_C93931A712469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_deliveries (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, start INT NOT NULL, end INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_4919D51612469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_leads (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, value INT NOT NULL, created_at DATETIME NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_FFA30A1B12469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities (id INT AUTO_INCREMENT NOT NULL, province_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, coordinates MULTIPOLYGON DEFAULT NULL COMMENT \'(DC2Type:multipolygon)\', created_at DATETIME NOT NULL, INDEX IDX_D95DB16BE946114A (province_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE city_zones (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE city_zone_city (city_zone_id INT NOT NULL, city_id INT NOT NULL, INDEX IDX_1BF7DF84226481F9 (city_zone_id), INDEX IDX_1BF7DF848BAC62AF (city_id), PRIMARY KEY(city_zone_id, city_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE configurations (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, value LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_31C6AD977153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer_accounts (id INT AUTO_INCREMENT NOT NULL, customer_id INT NOT NULL, bank VARCHAR(255) DEFAULT NULL, sheba_number VARCHAR(255) DEFAULT NULL, card_number VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_E60DDD839395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer_addresses (id INT AUTO_INCREMENT NOT NULL, province_id INT NOT NULL, city_id INT NOT NULL, district_id INT DEFAULT NULL, customer_id INT NOT NULL, full_address LONGTEXT NOT NULL, postal_code VARCHAR(255) NOT NULL, is_default TINYINT(1) NOT NULL, coordinates POINT DEFAULT NULL COMMENT \'(DC2Type:point)\', number INT NOT NULL, unit INT DEFAULT NULL, name VARCHAR(255) NOT NULL, family VARCHAR(255) NOT NULL, national_code VARCHAR(10) NOT NULL, mobile VARCHAR(15) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_C4378D0CE946114A (province_id), INDEX IDX_C4378D0C8BAC62AF (city_id), INDEX IDX_C4378D0CB08FA272 (district_id), INDEX IDX_C4378D0C9395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customers (id INT AUTO_INCREMENT NOT NULL, roles LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, family VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, gender VARCHAR(255) DEFAULT NULL, birthday DATE DEFAULT NULL, mobile VARCHAR(15) NOT NULL, national_number VARCHAR(10) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_62534E21E7927C74 (email), UNIQUE INDEX UNIQ_62534E213C7323E0 (mobile), UNIQUE INDEX UNIQ_62534E21946B2122 (national_number), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE district_zones (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE district_zone_district (district_zone_id INT NOT NULL, district_id INT NOT NULL, INDEX IDX_BB45805223F5C396 (district_zone_id), INDEX IDX_BB458052B08FA272 (district_id), PRIMARY KEY(district_zone_id, district_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE districts (id INT AUTO_INCREMENT NOT NULL, city_id INT NOT NULL, name VARCHAR(255) NOT NULL, coordinates MULTIPOLYGON DEFAULT NULL COMMENT \'(DC2Type:multipolygon)\', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_68E318DC8BAC62AF (city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE documents (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(8) NOT NULL, amount BIGINT UNSIGNED NOT NULL, completed_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, document_type VARCHAR(32) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ext_log_entries (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', username VARCHAR(255) DEFAULT NULL, INDEX log_class_lookup_idx (object_class), INDEX log_date_lookup_idx (logged_at), INDEX log_user_lookup_idx (username), INDEX log_version_lookup_idx (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE generic_zones (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE generic_zone_zone (generic_zone_id INT NOT NULL, zone_id INT NOT NULL, INDEX IDX_44D3911D22621DFA (generic_zone_id), INDEX IDX_44D3911D9F2C3FAB (zone_id), PRIMARY KEY(generic_zone_id, zone_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE holidays (id INT AUTO_INCREMENT NOT NULL, seller_id INT NOT NULL, title VARCHAR(255) NOT NULL, date DATE NOT NULL, supply TINYINT(1) NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_3A66A10C8DE820D9 (seller_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inventories (id INT AUTO_INCREMENT NOT NULL, variant_id INT NOT NULL, seller_id INT NOT NULL, stock INT NOT NULL, price BIGINT UNSIGNED NOT NULL, final_price BIGINT UNSIGNED NOT NULL, is_trackable TINYINT(1) NOT NULL, is_active TINYINT(1) NOT NULL, max_purchase_per_order INT NOT NULL, supplies_in INT NOT NULL, order_count INT NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_936C863D3B69A9AF (variant_id), INDEX IDX_936C863D8DE820D9 (seller_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE medias (id INT AUTO_INCREMENT NOT NULL, path VARCHAR(255) NOT NULL, alt VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, discr VARCHAR(255) NOT NULL, entity_id INT NOT NULL, INDEX IDX_12D2AF8181257D5D (entity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_addresses (id INT AUTO_INCREMENT NOT NULL, district_id INT NOT NULL, city_id INT NOT NULL, order_id INT NOT NULL, full_address LONGTEXT NOT NULL, unit INT NOT NULL, number INT NOT NULL, coordinates POINT DEFAULT NULL COMMENT \'(DC2Type:point)\', name VARCHAR(255) NOT NULL, family VARCHAR(255) NOT NULL, national_code VARCHAR(10) NOT NULL, phone VARCHAR(255) NOT NULL, postal_code INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_D34D0EEEB08FA272 (district_id), INDEX IDX_D34D0EEE8BAC62AF (city_id), UNIQUE INDEX UNIQ_D34D0EEE8D9F6D38 (order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_conditions (id INT AUTO_INCREMENT NOT NULL, order_id INT NOT NULL, code VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, target VARCHAR(255) NOT NULL, value DOUBLE PRECISION NOT NULL, description LONGTEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_47BCF4FC8D9F6D38 (order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_documents (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_items (id INT AUTO_INCREMENT NOT NULL, inventory_id INT NOT NULL, order_id INT NOT NULL, order_shipment_id INT DEFAULT NULL, subtotal BIGINT UNSIGNED NOT NULL, grand_total BIGINT UNSIGNED NOT NULL, quantity INT NOT NULL, price BIGINT UNSIGNED NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_62809DB09EEA759 (inventory_id), INDEX IDX_62809DB08D9F6D38 (order_id), INDEX IDX_62809DB06052497A (order_shipment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_notes (id INT AUTO_INCREMENT NOT NULL, order_id INT NOT NULL, admin_id INT NOT NULL, description LONGTEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_8285D2718D9F6D38 (order_id), INDEX IDX_8285D271642B8210 (admin_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_shipment_status_logs (id INT AUTO_INCREMENT NOT NULL, order_shipment_id INT DEFAULT NULL, user_id INT DEFAULT NULL, status_from VARCHAR(255) NOT NULL, status_to VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_5973A5746052497A (order_shipment_id), INDEX IDX_5973A574A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_shipments (id INT AUTO_INCREMENT NOT NULL, method_id INT NOT NULL, order_id INT NOT NULL, transaction_id INT DEFAULT NULL, period_id INT DEFAULT NULL, shipping_category_id INT NOT NULL, sub_total BIGINT UNSIGNED NOT NULL, grand_total BIGINT UNSIGNED NOT NULL, status VARCHAR(255) NOT NULL, signature VARCHAR(255) DEFAULT NULL, tracking_code VARCHAR(255) DEFAULT NULL, title VARCHAR(255) NOT NULL, category_delivery_range LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', delivery_date DATE NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_28EEE12C19883967 (method_id), INDEX IDX_28EEE12C8D9F6D38 (order_id), INDEX IDX_28EEE12C2FC0CB0F (transaction_id), INDEX IDX_28EEE12CEC8B7ADE (period_id), INDEX IDX_28EEE12C9E2D1A41 (shipping_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_status_logs (id INT AUTO_INCREMENT NOT NULL, order_id INT DEFAULT NULL, user_id INT DEFAULT NULL, status_from VARCHAR(255) NOT NULL, status_to VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_D33B144E8D9F6D38 (order_id), INDEX IDX_D33B144EA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE orders (id INT AUTO_INCREMENT NOT NULL, customer_id INT NOT NULL, address_id INT DEFAULT NULL, order_document_id INT NOT NULL, status VARCHAR(255) NOT NULL, identifier VARCHAR(255) DEFAULT NULL, subtotal BIGINT UNSIGNED NOT NULL, grand_total BIGINT UNSIGNED NOT NULL, payment_method VARCHAR(255) NOT NULL, completed_at DATETIME DEFAULT NULL, paid_at DATETIME DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_E52FFDEE772E836A (identifier), INDEX IDX_E52FFDEE9395C3F3 (customer_id), INDEX IDX_E52FFDEEF5B7AF75 (address_id), UNIQUE INDEX UNIQ_E52FFDEED88D07B1 (order_document_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_option_values (id INT AUTO_INCREMENT NOT NULL, option_id INT NOT NULL, value VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, attributes LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', INDEX IDX_A31A52C3A7C41D6F (option_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_options (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_variants (id INT AUTO_INCREMENT NOT NULL, product_id INT NOT NULL, code VARCHAR(255) NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_7828397677153098 (code), INDEX IDX_782839764584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_variant_product_option_value (product_variant_id INT NOT NULL, product_option_value_id INT NOT NULL, INDEX IDX_612C6EDDA80EF684 (product_variant_id), INDEX IDX_612C6EDDEBDCCF9B (product_option_value_id), PRIMARY KEY(product_variant_id, product_option_value_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE products (id INT AUTO_INCREMENT NOT NULL, brand_id INT NOT NULL, shipping_category_id INT NOT NULL, category_id INT NOT NULL, seller_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, subtitle VARCHAR(255) DEFAULT NULL, code VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, meta_description LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, is_original TINYINT(1) NOT NULL, status VARCHAR(255) NOT NULL, length DOUBLE PRECISION DEFAULT NULL, width DOUBLE PRECISION DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, visits INT NOT NULL, order_count INT NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_B3BA5A5A518597B1 (subtitle), UNIQUE INDEX UNIQ_B3BA5A5A77153098 (code), INDEX IDX_B3BA5A5A44F5D008 (brand_id), INDEX IDX_B3BA5A5A9E2D1A41 (shipping_category_id), INDEX IDX_B3BA5A5A12469DE2 (category_id), INDEX IDX_B3BA5A5A8DE820D9 (seller_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_product_option (product_id INT NOT NULL, product_option_id INT NOT NULL, INDEX IDX_6B933F384584665A (product_id), INDEX IDX_6B933F38C964ABE2 (product_option_id), PRIMARY KEY(product_id, product_option_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE province_zones (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE province_zone_province (province_zone_id INT NOT NULL, province_id INT NOT NULL, INDEX IDX_693BC74348649A77 (province_zone_id), INDEX IDX_693BC743E946114A (province_id), PRIMARY KEY(province_zone_id, province_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE provinces (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, coordinates MULTIPOLYGON DEFAULT NULL COMMENT \'(DC2Type:multipolygon)\', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_8C96CC5777153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE refund_documents (id INT NOT NULL, order_id INT NOT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_3BC8CC008D9F6D38 (order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seller_order_items (id INT AUTO_INCREMENT NOT NULL, order_item_id INT NOT NULL, seller_id INT NOT NULL, package_item_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_CF284E07E415FB15 (order_item_id), INDEX IDX_CF284E078DE820D9 (seller_id), INDEX IDX_CF284E079D3437D2 (package_item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seller_package_items (id INT AUTO_INCREMENT NOT NULL, package_id INT NOT NULL, quantity INT NOT NULL, description VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_C044F813F44CABFF (package_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seller_package_status_logs (id INT AUTO_INCREMENT NOT NULL, seller_package_id INT NOT NULL, user_id INT DEFAULT NULL, status_from VARCHAR(255) NOT NULL, status_to VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_3EB27F6C3B175A95 (seller_package_id), INDEX IDX_3EB27F6CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seller_packages (id INT AUTO_INCREMENT NOT NULL, seller_id INT NOT NULL, status VARCHAR(32) NOT NULL, sent_at DATETIME NOT NULL, description VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_F1DEEEEC8DE820D9 (seller_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sellers (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) NOT NULL, national_number VARCHAR(10) DEFAULT NULL, national_identifier VARCHAR(255) DEFAULT NULL, is_limited TINYINT(1) DEFAULT \'0\' NOT NULL, identifier INT DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_AFFE6BEF77153098 (code), UNIQUE INDEX UNIQ_AFFE6BEF946B2122 (national_number), UNIQUE INDEX UNIQ_AFFE6BEFEC9EDEA (national_identifier), UNIQUE INDEX UNIQ_AFFE6BEF772E836A (identifier), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shipping_categories (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_820816365E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shipping_category_shipping_method (shipping_category_id INT NOT NULL, shipping_method_id INT NOT NULL, INDEX IDX_18C7DFCD9E2D1A41 (shipping_category_id), INDEX IDX_18C7DFCD5F7D6850 (shipping_method_id), PRIMARY KEY(shipping_category_id, shipping_method_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shipping_method_price (id INT AUTO_INCREMENT NOT NULL, zone_id INT NOT NULL, shipping_method_id INT NOT NULL, price BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_3CE1BB7F9F2C3FAB (zone_id), INDEX IDX_3CE1BB7F5F7D6850 (shipping_method_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shipping_methods (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(30) NOT NULL, configuration LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_B0AAF1AD5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shipping_periods (id INT AUTO_INCREMENT NOT NULL, start TIME NOT NULL, end TIME NOT NULL, is_active TINYINT(1) NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transactions (id INT AUTO_INCREMENT NOT NULL, document_id INT NOT NULL, status VARCHAR(255) NOT NULL, amount BIGINT UNSIGNED NOT NULL, gateway VARCHAR(255) NOT NULL, reference_number VARCHAR(255) DEFAULT NULL, tracking_number VARCHAR(255) DEFAULT NULL, identifier VARCHAR(255) DEFAULT NULL, paid_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_EAA81A4CC33F7837 (document_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE warehouses (id INT AUTO_INCREMENT NOT NULL, seller_id INT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_AFE9C2B777153098 (code), INDEX IDX_AFE9C2B78DE820D9 (seller_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wishlists (id INT AUTO_INCREMENT NOT NULL, customer_id INT NOT NULL, product_id INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_4A4C2E1B9395C3F3 (customer_id), INDEX IDX_4A4C2E1B4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE zones (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, dtype VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT FK_BEF484459EEA759 FOREIGN KEY (inventory_id) REFERENCES inventories (id)');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT FK_BEF484451AD5CDBF FOREIGN KEY (cart_id) REFERENCES carts (id)');
        $this->addSql('ALTER TABLE carts ADD CONSTRAINT FK_4E004AAC9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id)');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF34668727ACA70 FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE category_closures ADD CONSTRAINT FK_5DE8AEBFB4465BB FOREIGN KEY (ancestor) REFERENCES categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category_closures ADD CONSTRAINT FK_5DE8AEBF9A8FAD16 FOREIGN KEY (descendant) REFERENCES categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category_commissions ADD CONSTRAINT FK_C93931A712469DE2 FOREIGN KEY (category_id) REFERENCES categories (id)');
        $this->addSql('ALTER TABLE category_deliveries ADD CONSTRAINT FK_4919D51612469DE2 FOREIGN KEY (category_id) REFERENCES categories (id)');
        $this->addSql('ALTER TABLE category_leads ADD CONSTRAINT FK_FFA30A1B12469DE2 FOREIGN KEY (category_id) REFERENCES categories (id)');
        $this->addSql('ALTER TABLE cities ADD CONSTRAINT FK_D95DB16BE946114A FOREIGN KEY (province_id) REFERENCES provinces (id)');
        $this->addSql('ALTER TABLE city_zones ADD CONSTRAINT FK_C640163FBF396750 FOREIGN KEY (id) REFERENCES zones (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE city_zone_city ADD CONSTRAINT FK_1BF7DF84226481F9 FOREIGN KEY (city_zone_id) REFERENCES city_zones (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE city_zone_city ADD CONSTRAINT FK_1BF7DF848BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer_accounts ADD CONSTRAINT FK_E60DDD839395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id)');
        $this->addSql('ALTER TABLE customer_addresses ADD CONSTRAINT FK_C4378D0CE946114A FOREIGN KEY (province_id) REFERENCES provinces (id)');
        $this->addSql('ALTER TABLE customer_addresses ADD CONSTRAINT FK_C4378D0C8BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE customer_addresses ADD CONSTRAINT FK_C4378D0CB08FA272 FOREIGN KEY (district_id) REFERENCES districts (id)');
        $this->addSql('ALTER TABLE customer_addresses ADD CONSTRAINT FK_C4378D0C9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id)');
        $this->addSql('ALTER TABLE district_zones ADD CONSTRAINT FK_2A8C165BBF396750 FOREIGN KEY (id) REFERENCES zones (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE district_zone_district ADD CONSTRAINT FK_BB45805223F5C396 FOREIGN KEY (district_zone_id) REFERENCES district_zones (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE district_zone_district ADD CONSTRAINT FK_BB458052B08FA272 FOREIGN KEY (district_id) REFERENCES districts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE districts ADD CONSTRAINT FK_68E318DC8BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE generic_zones ADD CONSTRAINT FK_ECF6097ABF396750 FOREIGN KEY (id) REFERENCES zones (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE generic_zone_zone ADD CONSTRAINT FK_44D3911D22621DFA FOREIGN KEY (generic_zone_id) REFERENCES generic_zones (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE generic_zone_zone ADD CONSTRAINT FK_44D3911D9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zones (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE holidays ADD CONSTRAINT FK_3A66A10C8DE820D9 FOREIGN KEY (seller_id) REFERENCES sellers (id)');
        $this->addSql('ALTER TABLE inventories ADD CONSTRAINT FK_936C863D3B69A9AF FOREIGN KEY (variant_id) REFERENCES product_variants (id)');
        $this->addSql('ALTER TABLE inventories ADD CONSTRAINT FK_936C863D8DE820D9 FOREIGN KEY (seller_id) REFERENCES sellers (id)');
        $this->addSql('ALTER TABLE order_addresses ADD CONSTRAINT FK_D34D0EEEB08FA272 FOREIGN KEY (district_id) REFERENCES districts (id)');
        $this->addSql('ALTER TABLE order_addresses ADD CONSTRAINT FK_D34D0EEE8BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE order_addresses ADD CONSTRAINT FK_D34D0EEE8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE order_conditions ADD CONSTRAINT FK_47BCF4FC8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE order_documents ADD CONSTRAINT FK_1E370970BF396750 FOREIGN KEY (id) REFERENCES documents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_items ADD CONSTRAINT FK_62809DB09EEA759 FOREIGN KEY (inventory_id) REFERENCES inventories (id)');
        $this->addSql('ALTER TABLE order_items ADD CONSTRAINT FK_62809DB08D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE order_items ADD CONSTRAINT FK_62809DB06052497A FOREIGN KEY (order_shipment_id) REFERENCES order_shipments (id)');
        $this->addSql('ALTER TABLE order_notes ADD CONSTRAINT FK_8285D2718D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE order_notes ADD CONSTRAINT FK_8285D271642B8210 FOREIGN KEY (admin_id) REFERENCES admins (id)');
        $this->addSql('ALTER TABLE order_shipment_status_logs ADD CONSTRAINT FK_5973A5746052497A FOREIGN KEY (order_shipment_id) REFERENCES order_shipments (id)');
        $this->addSql('ALTER TABLE order_shipment_status_logs ADD CONSTRAINT FK_5973A574A76ED395 FOREIGN KEY (user_id) REFERENCES admins (id)');
        $this->addSql('ALTER TABLE order_shipments ADD CONSTRAINT FK_28EEE12C19883967 FOREIGN KEY (method_id) REFERENCES shipping_methods (id)');
        $this->addSql('ALTER TABLE order_shipments ADD CONSTRAINT FK_28EEE12C8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE order_shipments ADD CONSTRAINT FK_28EEE12C2FC0CB0F FOREIGN KEY (transaction_id) REFERENCES transactions (id)');
        $this->addSql('ALTER TABLE order_shipments ADD CONSTRAINT FK_28EEE12CEC8B7ADE FOREIGN KEY (period_id) REFERENCES shipping_periods (id)');
        $this->addSql('ALTER TABLE order_shipments ADD CONSTRAINT FK_28EEE12C9E2D1A41 FOREIGN KEY (shipping_category_id) REFERENCES shipping_categories (id)');
        $this->addSql('ALTER TABLE order_status_logs ADD CONSTRAINT FK_D33B144E8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE order_status_logs ADD CONSTRAINT FK_D33B144EA76ED395 FOREIGN KEY (user_id) REFERENCES admins (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEF5B7AF75 FOREIGN KEY (address_id) REFERENCES customer_addresses (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEED88D07B1 FOREIGN KEY (order_document_id) REFERENCES order_documents (id)');
        $this->addSql('ALTER TABLE product_option_values ADD CONSTRAINT FK_A31A52C3A7C41D6F FOREIGN KEY (option_id) REFERENCES product_options (id)');
        $this->addSql('ALTER TABLE product_variants ADD CONSTRAINT FK_782839764584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE product_variant_product_option_value ADD CONSTRAINT FK_612C6EDDA80EF684 FOREIGN KEY (product_variant_id) REFERENCES product_variants (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_variant_product_option_value ADD CONSTRAINT FK_612C6EDDEBDCCF9B FOREIGN KEY (product_option_value_id) REFERENCES product_option_values (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A44F5D008 FOREIGN KEY (brand_id) REFERENCES brands (id)');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A9E2D1A41 FOREIGN KEY (shipping_category_id) REFERENCES shipping_categories (id)');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A12469DE2 FOREIGN KEY (category_id) REFERENCES categories (id)');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A8DE820D9 FOREIGN KEY (seller_id) REFERENCES sellers (id)');
        $this->addSql('ALTER TABLE product_product_option ADD CONSTRAINT FK_6B933F384584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_product_option ADD CONSTRAINT FK_6B933F38C964ABE2 FOREIGN KEY (product_option_id) REFERENCES product_options (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE province_zones ADD CONSTRAINT FK_2DA42545BF396750 FOREIGN KEY (id) REFERENCES zones (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE province_zone_province ADD CONSTRAINT FK_693BC74348649A77 FOREIGN KEY (province_zone_id) REFERENCES province_zones (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE province_zone_province ADD CONSTRAINT FK_693BC743E946114A FOREIGN KEY (province_id) REFERENCES provinces (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE refund_documents ADD CONSTRAINT FK_3BC8CC008D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE refund_documents ADD CONSTRAINT FK_3BC8CC00BF396750 FOREIGN KEY (id) REFERENCES documents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE seller_order_items ADD CONSTRAINT FK_CF284E07E415FB15 FOREIGN KEY (order_item_id) REFERENCES order_items (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE seller_order_items ADD CONSTRAINT FK_CF284E078DE820D9 FOREIGN KEY (seller_id) REFERENCES sellers (id)');
        $this->addSql('ALTER TABLE seller_order_items ADD CONSTRAINT FK_CF284E079D3437D2 FOREIGN KEY (package_item_id) REFERENCES seller_package_items (id)');
        $this->addSql('ALTER TABLE seller_package_items ADD CONSTRAINT FK_C044F813F44CABFF FOREIGN KEY (package_id) REFERENCES seller_packages (id)');
        $this->addSql('ALTER TABLE seller_package_status_logs ADD CONSTRAINT FK_3EB27F6C3B175A95 FOREIGN KEY (seller_package_id) REFERENCES seller_packages (id)');
        $this->addSql('ALTER TABLE seller_package_status_logs ADD CONSTRAINT FK_3EB27F6CA76ED395 FOREIGN KEY (user_id) REFERENCES admins (id)');
        $this->addSql('ALTER TABLE seller_packages ADD CONSTRAINT FK_F1DEEEEC8DE820D9 FOREIGN KEY (seller_id) REFERENCES sellers (id)');
        $this->addSql('ALTER TABLE shipping_category_shipping_method ADD CONSTRAINT FK_18C7DFCD9E2D1A41 FOREIGN KEY (shipping_category_id) REFERENCES shipping_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shipping_category_shipping_method ADD CONSTRAINT FK_18C7DFCD5F7D6850 FOREIGN KEY (shipping_method_id) REFERENCES shipping_methods (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shipping_method_price ADD CONSTRAINT FK_3CE1BB7F9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zones (id)');
        $this->addSql('ALTER TABLE shipping_method_price ADD CONSTRAINT FK_3CE1BB7F5F7D6850 FOREIGN KEY (shipping_method_id) REFERENCES shipping_methods (id)');
        $this->addSql('ALTER TABLE transactions ADD CONSTRAINT FK_EAA81A4CC33F7837 FOREIGN KEY (document_id) REFERENCES documents (id)');
        $this->addSql('ALTER TABLE warehouses ADD CONSTRAINT FK_AFE9C2B78DE820D9 FOREIGN KEY (seller_id) REFERENCES sellers (id)');
        $this->addSql('ALTER TABLE wishlists ADD CONSTRAINT FK_4A4C2E1B9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id)');
        $this->addSql('ALTER TABLE wishlists ADD CONSTRAINT FK_4A4C2E1B4584665A FOREIGN KEY (product_id) REFERENCES products (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE order_notes DROP FOREIGN KEY FK_8285D271642B8210');
        $this->addSql('ALTER TABLE order_shipment_status_logs DROP FOREIGN KEY FK_5973A574A76ED395');
        $this->addSql('ALTER TABLE order_status_logs DROP FOREIGN KEY FK_D33B144EA76ED395');
        $this->addSql('ALTER TABLE seller_package_status_logs DROP FOREIGN KEY FK_3EB27F6CA76ED395');
        $this->addSql('ALTER TABLE products DROP FOREIGN KEY FK_B3BA5A5A44F5D008');
        $this->addSql('ALTER TABLE cart_items DROP FOREIGN KEY FK_BEF484451AD5CDBF');
        $this->addSql('ALTER TABLE categories DROP FOREIGN KEY FK_3AF34668727ACA70');
        $this->addSql('ALTER TABLE category_closures DROP FOREIGN KEY FK_5DE8AEBFB4465BB');
        $this->addSql('ALTER TABLE category_closures DROP FOREIGN KEY FK_5DE8AEBF9A8FAD16');
        $this->addSql('ALTER TABLE category_commissions DROP FOREIGN KEY FK_C93931A712469DE2');
        $this->addSql('ALTER TABLE category_deliveries DROP FOREIGN KEY FK_4919D51612469DE2');
        $this->addSql('ALTER TABLE category_leads DROP FOREIGN KEY FK_FFA30A1B12469DE2');
        $this->addSql('ALTER TABLE products DROP FOREIGN KEY FK_B3BA5A5A12469DE2');
        $this->addSql('ALTER TABLE city_zone_city DROP FOREIGN KEY FK_1BF7DF848BAC62AF');
        $this->addSql('ALTER TABLE customer_addresses DROP FOREIGN KEY FK_C4378D0C8BAC62AF');
        $this->addSql('ALTER TABLE districts DROP FOREIGN KEY FK_68E318DC8BAC62AF');
        $this->addSql('ALTER TABLE order_addresses DROP FOREIGN KEY FK_D34D0EEE8BAC62AF');
        $this->addSql('ALTER TABLE city_zone_city DROP FOREIGN KEY FK_1BF7DF84226481F9');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEEF5B7AF75');
        $this->addSql('ALTER TABLE carts DROP FOREIGN KEY FK_4E004AAC9395C3F3');
        $this->addSql('ALTER TABLE customer_accounts DROP FOREIGN KEY FK_E60DDD839395C3F3');
        $this->addSql('ALTER TABLE customer_addresses DROP FOREIGN KEY FK_C4378D0C9395C3F3');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE9395C3F3');
        $this->addSql('ALTER TABLE wishlists DROP FOREIGN KEY FK_4A4C2E1B9395C3F3');
        $this->addSql('ALTER TABLE district_zone_district DROP FOREIGN KEY FK_BB45805223F5C396');
        $this->addSql('ALTER TABLE customer_addresses DROP FOREIGN KEY FK_C4378D0CB08FA272');
        $this->addSql('ALTER TABLE district_zone_district DROP FOREIGN KEY FK_BB458052B08FA272');
        $this->addSql('ALTER TABLE order_addresses DROP FOREIGN KEY FK_D34D0EEEB08FA272');
        $this->addSql('ALTER TABLE order_documents DROP FOREIGN KEY FK_1E370970BF396750');
        $this->addSql('ALTER TABLE refund_documents DROP FOREIGN KEY FK_3BC8CC00BF396750');
        $this->addSql('ALTER TABLE transactions DROP FOREIGN KEY FK_EAA81A4CC33F7837');
        $this->addSql('ALTER TABLE generic_zone_zone DROP FOREIGN KEY FK_44D3911D22621DFA');
        $this->addSql('ALTER TABLE cart_items DROP FOREIGN KEY FK_BEF484459EEA759');
        $this->addSql('ALTER TABLE order_items DROP FOREIGN KEY FK_62809DB09EEA759');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEED88D07B1');
        $this->addSql('ALTER TABLE seller_order_items DROP FOREIGN KEY FK_CF284E07E415FB15');
        $this->addSql('ALTER TABLE order_items DROP FOREIGN KEY FK_62809DB06052497A');
        $this->addSql('ALTER TABLE order_shipment_status_logs DROP FOREIGN KEY FK_5973A5746052497A');
        $this->addSql('ALTER TABLE order_addresses DROP FOREIGN KEY FK_D34D0EEE8D9F6D38');
        $this->addSql('ALTER TABLE order_conditions DROP FOREIGN KEY FK_47BCF4FC8D9F6D38');
        $this->addSql('ALTER TABLE order_items DROP FOREIGN KEY FK_62809DB08D9F6D38');
        $this->addSql('ALTER TABLE order_notes DROP FOREIGN KEY FK_8285D2718D9F6D38');
        $this->addSql('ALTER TABLE order_shipments DROP FOREIGN KEY FK_28EEE12C8D9F6D38');
        $this->addSql('ALTER TABLE order_status_logs DROP FOREIGN KEY FK_D33B144E8D9F6D38');
        $this->addSql('ALTER TABLE refund_documents DROP FOREIGN KEY FK_3BC8CC008D9F6D38');
        $this->addSql('ALTER TABLE product_variant_product_option_value DROP FOREIGN KEY FK_612C6EDDEBDCCF9B');
        $this->addSql('ALTER TABLE product_option_values DROP FOREIGN KEY FK_A31A52C3A7C41D6F');
        $this->addSql('ALTER TABLE product_product_option DROP FOREIGN KEY FK_6B933F38C964ABE2');
        $this->addSql('ALTER TABLE inventories DROP FOREIGN KEY FK_936C863D3B69A9AF');
        $this->addSql('ALTER TABLE product_variant_product_option_value DROP FOREIGN KEY FK_612C6EDDA80EF684');
        $this->addSql('ALTER TABLE product_variants DROP FOREIGN KEY FK_782839764584665A');
        $this->addSql('ALTER TABLE product_product_option DROP FOREIGN KEY FK_6B933F384584665A');
        $this->addSql('ALTER TABLE wishlists DROP FOREIGN KEY FK_4A4C2E1B4584665A');
        $this->addSql('ALTER TABLE province_zone_province DROP FOREIGN KEY FK_693BC74348649A77');
        $this->addSql('ALTER TABLE cities DROP FOREIGN KEY FK_D95DB16BE946114A');
        $this->addSql('ALTER TABLE customer_addresses DROP FOREIGN KEY FK_C4378D0CE946114A');
        $this->addSql('ALTER TABLE province_zone_province DROP FOREIGN KEY FK_693BC743E946114A');
        $this->addSql('ALTER TABLE seller_order_items DROP FOREIGN KEY FK_CF284E079D3437D2');
        $this->addSql('ALTER TABLE seller_package_items DROP FOREIGN KEY FK_C044F813F44CABFF');
        $this->addSql('ALTER TABLE seller_package_status_logs DROP FOREIGN KEY FK_3EB27F6C3B175A95');
        $this->addSql('ALTER TABLE holidays DROP FOREIGN KEY FK_3A66A10C8DE820D9');
        $this->addSql('ALTER TABLE inventories DROP FOREIGN KEY FK_936C863D8DE820D9');
        $this->addSql('ALTER TABLE products DROP FOREIGN KEY FK_B3BA5A5A8DE820D9');
        $this->addSql('ALTER TABLE seller_order_items DROP FOREIGN KEY FK_CF284E078DE820D9');
        $this->addSql('ALTER TABLE seller_packages DROP FOREIGN KEY FK_F1DEEEEC8DE820D9');
        $this->addSql('ALTER TABLE warehouses DROP FOREIGN KEY FK_AFE9C2B78DE820D9');
        $this->addSql('ALTER TABLE order_shipments DROP FOREIGN KEY FK_28EEE12C9E2D1A41');
        $this->addSql('ALTER TABLE products DROP FOREIGN KEY FK_B3BA5A5A9E2D1A41');
        $this->addSql('ALTER TABLE shipping_category_shipping_method DROP FOREIGN KEY FK_18C7DFCD9E2D1A41');
        $this->addSql('ALTER TABLE order_shipments DROP FOREIGN KEY FK_28EEE12C19883967');
        $this->addSql('ALTER TABLE shipping_category_shipping_method DROP FOREIGN KEY FK_18C7DFCD5F7D6850');
        $this->addSql('ALTER TABLE shipping_method_price DROP FOREIGN KEY FK_3CE1BB7F5F7D6850');
        $this->addSql('ALTER TABLE order_shipments DROP FOREIGN KEY FK_28EEE12CEC8B7ADE');
        $this->addSql('ALTER TABLE order_shipments DROP FOREIGN KEY FK_28EEE12C2FC0CB0F');
        $this->addSql('ALTER TABLE city_zones DROP FOREIGN KEY FK_C640163FBF396750');
        $this->addSql('ALTER TABLE district_zones DROP FOREIGN KEY FK_2A8C165BBF396750');
        $this->addSql('ALTER TABLE generic_zones DROP FOREIGN KEY FK_ECF6097ABF396750');
        $this->addSql('ALTER TABLE generic_zone_zone DROP FOREIGN KEY FK_44D3911D9F2C3FAB');
        $this->addSql('ALTER TABLE province_zones DROP FOREIGN KEY FK_2DA42545BF396750');
        $this->addSql('ALTER TABLE shipping_method_price DROP FOREIGN KEY FK_3CE1BB7F9F2C3FAB');
        $this->addSql('DROP TABLE admins');
        $this->addSql('DROP TABLE brands');
        $this->addSql('DROP TABLE cart_items');
        $this->addSql('DROP TABLE carts');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE category_closures');
        $this->addSql('DROP TABLE category_commissions');
        $this->addSql('DROP TABLE category_deliveries');
        $this->addSql('DROP TABLE category_leads');
        $this->addSql('DROP TABLE cities');
        $this->addSql('DROP TABLE city_zones');
        $this->addSql('DROP TABLE city_zone_city');
        $this->addSql('DROP TABLE configurations');
        $this->addSql('DROP TABLE customer_accounts');
        $this->addSql('DROP TABLE customer_addresses');
        $this->addSql('DROP TABLE customers');
        $this->addSql('DROP TABLE district_zones');
        $this->addSql('DROP TABLE district_zone_district');
        $this->addSql('DROP TABLE districts');
        $this->addSql('DROP TABLE documents');
        $this->addSql('DROP TABLE ext_log_entries');
        $this->addSql('DROP TABLE generic_zones');
        $this->addSql('DROP TABLE generic_zone_zone');
        $this->addSql('DROP TABLE holidays');
        $this->addSql('DROP TABLE inventories');
        $this->addSql('DROP TABLE medias');
        $this->addSql('DROP TABLE order_addresses');
        $this->addSql('DROP TABLE order_conditions');
        $this->addSql('DROP TABLE order_documents');
        $this->addSql('DROP TABLE order_items');
        $this->addSql('DROP TABLE order_notes');
        $this->addSql('DROP TABLE order_shipment_status_logs');
        $this->addSql('DROP TABLE order_shipments');
        $this->addSql('DROP TABLE order_status_logs');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE product_option_values');
        $this->addSql('DROP TABLE product_options');
        $this->addSql('DROP TABLE product_variants');
        $this->addSql('DROP TABLE product_variant_product_option_value');
        $this->addSql('DROP TABLE products');
        $this->addSql('DROP TABLE product_product_option');
        $this->addSql('DROP TABLE province_zones');
        $this->addSql('DROP TABLE province_zone_province');
        $this->addSql('DROP TABLE provinces');
        $this->addSql('DROP TABLE refund_documents');
        $this->addSql('DROP TABLE seller_order_items');
        $this->addSql('DROP TABLE seller_package_items');
        $this->addSql('DROP TABLE seller_package_status_logs');
        $this->addSql('DROP TABLE seller_packages');
        $this->addSql('DROP TABLE sellers');
        $this->addSql('DROP TABLE shipping_categories');
        $this->addSql('DROP TABLE shipping_category_shipping_method');
        $this->addSql('DROP TABLE shipping_method_price');
        $this->addSql('DROP TABLE shipping_methods');
        $this->addSql('DROP TABLE shipping_periods');
        $this->addSql('DROP TABLE transactions');
        $this->addSql('DROP TABLE warehouses');
        $this->addSql('DROP TABLE wishlists');
        $this->addSql('DROP TABLE zones');
    }
}
