monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        graylog_debug:
            type: gelf
            publisher: { hostname: '%env(GRAYLOG_HOST)%', port: '%env(GRAYLOG_PORT)%' }
            level: debug
            channels: [ "app" ]
        graylog_error:
            type: fingers_crossed
            action_level: error
            handler: gelf
            excluded_http_codes: [ 404, 405, 422 ]
            buffer_size: 50
        gelf:
            type: gelf
            publisher: { hostname: '%env(GRAYLOG_HOST)%', port: '%env(GRAYLOG_PORT)%' }
            level: debug