<?php

namespace App\DataFixtures;

use App\Entity\OrderItem;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;

class OrderItemFixtures extends BaseFixture implements DependentFixtureInterface
{
    protected function loadData(): void
    {
        $this->setReferenceAndPersist(
            'order_item_1',
            $this->createOrderItem(
                'order_1',
                'inventory_1',
                90000,
                80000,
                1,
                90000,
                90000,
                $this->faker->numberBetween(2, 10)
            )
        );
        $this->setReferenceAndPersist(
            'order_item_2',
            $this->createOrderItem(
                'order_1',
                'inventory_2',
                210000,
                210000,
                2,
                105000,
                105000,
                $this->faker->numberBetween(2, 10)
            )
        );
        $this->setReferenceAndPersist(
            'order_item_3',
            $this->createOrderItem(
                'order_2',
                'inventory_2',
                210000,
                210000,
                2,
                105000,
                105000,
                $this->faker->numberBetween(2, 10)
            )
        );
        $this->setReferenceAndPersist(
            'order_item_4',
            $this->createOrderItem(
                'order_2',
                'inventory_3',
                400000,
                390000,
                2,
                200000,
                195000,
                $this->faker->numberBetween(2, 10)
            )
        );
        $this->setReferenceAndPersist(
            'order_item_5',
            $this->createOrderItem(
                'order_3',
                'inventory_2',
                210000,
                200000,
                2,
                105000,
                100000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_6',
            $this->createOrderItem(
                'order_3',
                'inventory_3',
                400000,
                390000,
                2,
                200000,
                195000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_7',
            $this->createOrderItem(
                'order_4',
                'inventory_2',
                210000,
                200000,
                2,
                105000,
                100000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_8',
            $this->createOrderItem(
                'order_4',
                'inventory_3',
                400000,
                400000,
                2,
                200000,
                200000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_9',
            $this->createOrderItem(
                'order_5',
                'inventory_2',
                105000,
                100000,
                1,
                105000,
                100000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_10',
            $this->createOrderItem(
                'order_5',
                'inventory_4',
                249000,
                249000,
                1,
                249000,
                249000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_11',
            $this->createOrderItem(
                'order_6',
                'inventory_3',
                200000,
                200000,
                1,
                200000,
                200000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_12',
            $this->createOrderItem(
                'order_6',
                'inventory_4',
                498000,
                480000,
                2,
                249000,
                240000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_13',
            $this->createOrderItem(
                'order_7',
                'inventory_5',
                245000,
                245000,
                1,
                245000,
                245000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_14',
            $this->createOrderItem(
                'order_8',
                'inventory_6',
                279000,
                275000,
                2,
                139500,
                137500,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_15',
            $this->createOrderItem(
                'order_9',
                'inventory_6',
                279000,
                275000,
                2,
                139500,
                137500,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_16',
            $this->createOrderItem(
                'order_10',
                'inventory_21',
                5986000,
                5986000,
                1,
                5986000,
                5986000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_17',
            $this->createOrderItem(
                'order_10',
                'inventory_22',
                15000,
                15000,
                1,
                15000,
                15000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_18',
            $this->createOrderItem(
                'order_11',
                'inventory_6',
                279000,
                275000,
                2,
                139500,
                137500,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_19',
            $this->createOrderItem(
                'order_11',
                'inventory_6',
                380000,
                385000,
                1,
                139500,
                385000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_20',
            $this->createOrderItem(
                'order_11',
                'inventory_6',
                553000,
                670000,
                2,
                145500,
                335000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_21',
            $this->createOrderItem(
                'order_12',
                'inventory_24',
                600000,
                600000,
                6,
                100000,
                100000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_22',
            $this->createOrderItem(
                'order_13',
                'inventory_24',
                600000,
                600000,
                6,
                100000,
                100000,
            )
        );
        $this->setReferenceAndPersist(
            'order_item_23',
            $this->createOrderItem(
                'order_13',
                'inventory_24',
                600000,
                600000,
                6,
                100000,
                100000,
            )
        );

        $this->manager->flush();
    }

    /**
     * @inheritdoc
     */
    public function getDependencies(): array
    {
        return [
            OrderFixtures::class,
            InventoryFixtures::class,
        ];
    }

    private function createOrderItem(
        string $orderName,
        string $inventoryName,
        int $subtotal,
        int $grandTotal,
        int $quantity,
        int $price,
        int $finalPrice,
        ?int $leadTime = null,
    ): OrderItem {
        return (new OrderItem())
            ->setOrder($this->getReference($orderName))
            ->setInventory($this->getReference($inventoryName))
            ->setSubtotal($subtotal)
            ->setGrandTotal($grandTotal)
            ->setQuantity($quantity)
            ->setPrice($price)
            ->setFinalPrice($finalPrice)
            ->setLeadTime($leadTime);
    }
}
